package verify

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// The offline verifier reuses the product's own code for the two computations it must agree with
// byte for byte: the chain hash (internal/store/evidence.go, ADR-012) and the RFC 3161 token check
// (internal/anchor/verify.go and rfc3161.go). Importing those packages would pull the database
// driver, the configuration and the HTTP stack into a tool that must stay small, offline and
// copyable into the public rules repository (scripts/sync-public-rules.sh), so the code is mirrored
// mechanically instead: this test renders the mirror from the sources and fails when a file on disk
// differs. Regenerate after a change to a source with
//
//	go test ./internal/verify -run TestMirrorsMatchTheirSources -update-mirror
//
// In the public repository the sources are absent and the test skips: the mirror is the code.

var updateMirror = flag.Bool("update-mirror", false, "rewrite the mirrored files from internal/store and internal/anchor")

type mirror struct {
	out    string // relative to this package
	render func() ([]byte, error)
}

var mirrors = []mirror{
	{out: "zz_chainhash.go", render: renderChainHash},
	{out: filepath.Join("tsp", "zz_rfc3161.go"), render: func() ([]byte, error) { return renderWholeFile("rfc3161.go") }},
	{out: filepath.Join("tsp", "zz_verify.go"), render: func() ([]byte, error) { return renderWholeFile("verify.go") }},
}

func TestMirrorsMatchTheirSources(t *testing.T) {
	if _, err := os.Stat(filepath.Join("..", "store", "evidence.go")); errors.Is(err, fs.ErrNotExist) {
		t.Skip("the product sources are not here (public copy): the mirror is the code")
	}
	for _, m := range mirrors {
		got, err := m.render()
		require.NoError(t, err, m.out)
		if *updateMirror {
			require.NoError(t, os.WriteFile(m.out, got, 0o600), m.out)
			continue
		}
		onDisk, err := os.ReadFile(m.out)
		require.NoError(t, err, m.out)
		require.True(t, bytes.Equal(onDisk, got),
			"%s is stale: its source changed; run go test ./internal/verify -run TestMirrorsMatchTheirSources -update-mirror", m.out)
	}
}

const generatedHeader = "// Code generated by TestMirrorsMatchTheirSources from %s; DO NOT EDIT.\n" +
	"// Regenerate: go test ./internal/verify -run TestMirrorsMatchTheirSources -update-mirror\n\n"

// renderChainHash copies GenesisHash and ChainHash, with their comments, exactly as the store
// declares them.
func renderChainHash() ([]byte, error) {
	path := filepath.Join("..", "store", "evidence.go")
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var genesis, chain []byte
	for _, d := range f.Decls {
		switch d := d.(type) {
		case *ast.GenDecl:
			if d.Tok != token.CONST || len(d.Specs) != 1 {
				continue
			}
			if vs, ok := d.Specs[0].(*ast.ValueSpec); ok && len(vs.Names) == 1 && vs.Names[0].Name == "GenesisHash" {
				genesis = slice(fset, src, d.Doc, d)
			}
		case *ast.FuncDecl:
			if d.Recv == nil && d.Name.Name == "ChainHash" {
				chain = slice(fset, src, d.Doc, d)
			}
		}
	}
	if genesis == nil || chain == nil {
		return nil, fmt.Errorf("%s: GenesisHash or ChainHash not found as a single declaration", path)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, generatedHeader, "internal/store/evidence.go")
	b.WriteString("package verify\n\nimport (\n\t\"strconv\"\n\t\"strings\"\n\t\"time\"\n\n\t\"github.com/sixi-ai/sixi-assure-rules/model\"\n)\n\n")
	b.Write(genesis)
	b.WriteString("\n\n")
	b.Write(chain)
	b.WriteString("\n")
	return format.Source(b.Bytes())
}

// renderWholeFile copies one file of internal/anchor into package tsp: everything after the
// package clause, byte for byte; the package documentation stays with the source.
func renderWholeFile(name string) ([]byte, error) {
	path := filepath.Join("..", "anchor", name)
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, parser.ParseComments|parser.PackageClauseOnly)
	if err != nil {
		return nil, err
	}
	if f.Name.Name != "anchor" {
		return nil, fmt.Errorf("%s: package %s, want anchor", path, f.Name.Name)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, generatedHeader, "internal/anchor/"+name)
	b.WriteString("package tsp")
	b.Write(src[fset.Position(f.Name.End()).Offset:])
	return format.Source(b.Bytes())
}

// slice returns the source text of a declaration with its doc comment.
func slice(fset *token.FileSet, src []byte, doc *ast.CommentGroup, n ast.Node) []byte {
	start := n.Pos()
	if doc != nil {
		start = doc.Pos()
	}
	return bytes.Clone(src[fset.Position(start).Offset:fset.Position(n.End()).Offset])
}
