// Code generated by TestMirrorsMatchTheirSources from internal/store/evidence.go; DO NOT EDIT.
// Regenerate: go test ./internal/verify -run TestMirrorsMatchTheirSources -update-mirror

package verify

import (
	"strconv"
	"strings"
	"time"

	"github.com/sixi-ai/sixi-assure-rules/model"
)

// GenesisHash is the prev_hash of the first event of every architecture.
const GenesisHash = "0000000000000000000000000000000000000000000000000000000000000000"

// ChainHash computes an event hash exactly as stored (ADR-012):
// sha256(prev_hash|payload_hash|type|actor|version|ts) with ts in RFC 3339 nano, UTC.
// Timestamps are microsecond-truncated before hashing because PostgreSQL stores microseconds.
func ChainHash(prevHash, payloadHash, typ, actor string, version int, ts time.Time) string {
	parts := []string{prevHash, payloadHash, typ, actor, strconv.Itoa(version), ts.UTC().Truncate(time.Microsecond).Format(time.RFC3339Nano)}
	return model.HashBytes([]byte(strings.Join(parts, "|")))
}
