// Code generated by TestMirrorsMatchTheirSources from internal/anchor/rfc3161.go; DO NOT EDIT.
// Regenerate: go test ./internal/verify -run TestMirrorsMatchTheirSources -update-mirror

package tsp

import (
	"crypto"
	"crypto/rand"
	"crypto/x509/pkix"
	"encoding/asn1"
	"errors"
	"fmt"
	"math/big"
	"strings"
	"time"
)

// Errors a caller can test for.
var (
	// ErrMalformed is a request, reply or token that does not parse as the RFC defines it.
	ErrMalformed = errors.New("anchor: malformed time-stamp structure")
	// ErrRejected is a reply whose PKIStatus is neither granted nor grantedWithMods.
	ErrRejected = errors.New("anchor: the time-stamp authority refused the request")
	// ErrHashMismatch is a token over another hash than the one asked for.
	ErrHashMismatch = errors.New("anchor: the token covers another hash")
	// ErrNonceMismatch is a reply whose nonce is not the request's.
	ErrNonceMismatch = errors.New("anchor: the token carries another nonce")
	// ErrSignature is a token whose signature, signed attributes or signer do not verify.
	ErrSignature = errors.New("anchor: the token signature does not verify")
	// ErrUntrusted is a signer whose certificate does not chain to a trusted root, or is not a
	// time-stamping certificate.
	ErrUntrusted = errors.New("anchor: the token signer is not a trusted time-stamp authority")
)

// Object identifiers used below.
var (
	oidSignedData            = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 7, 2}
	oidTSTInfo               = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 9, 16, 1, 4}
	oidAttrContentType       = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 9, 3}
	oidAttrMessageDigest     = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 9, 4}
	oidAttrSigningCert       = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 9, 16, 2, 12}
	oidAttrSigningCertV2     = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 9, 16, 2, 47}
	oidSHA1                  = asn1.ObjectIdentifier{1, 3, 14, 3, 2, 26}
	oidSHA256                = asn1.ObjectIdentifier{2, 16, 840, 1, 101, 3, 4, 2, 1}
	oidSHA384                = asn1.ObjectIdentifier{2, 16, 840, 1, 101, 3, 4, 2, 2}
	oidSHA512                = asn1.ObjectIdentifier{2, 16, 840, 1, 101, 3, 4, 2, 3}
	oidExtKeyUsage           = asn1.ObjectIdentifier{2, 5, 29, 37}
	oidRSAEncryption         = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 1}
	oidSHA256WithRSA         = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 11}
	oidSHA384WithRSA         = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 12}
	oidSHA512WithRSA         = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 13}
	oidRSAPSS                = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 10}
	oidECPublicKey           = asn1.ObjectIdentifier{1, 2, 840, 10045, 2, 1}
	oidECDSAWithSHA256       = asn1.ObjectIdentifier{1, 2, 840, 10045, 4, 3, 2}
	oidECDSAWithSHA384       = asn1.ObjectIdentifier{1, 2, 840, 10045, 4, 3, 3}
	oidECDSAWithSHA512       = asn1.ObjectIdentifier{1, 2, 840, 10045, 4, 3, 4}
	oidEd25519               = asn1.ObjectIdentifier{1, 3, 101, 112}
	sha256AlgorithmIdentifer = pkix.AlgorithmIdentifier{Algorithm: oidSHA256, Parameters: asn1.NullRawValue}
)

// ---- wire structures (RFC 3161 §2.4, RFC 5652 §5) ------------------------------------------------

type messageImprint struct {
	HashAlgorithm pkix.AlgorithmIdentifier
	HashedMessage []byte
}

type timeStampReq struct {
	Version        int
	MessageImprint messageImprint
	ReqPolicy      asn1.ObjectIdentifier `asn1:"optional"`
	Nonce          *big.Int              `asn1:"optional"`
	CertReq        bool                  `asn1:"optional"`
	Extensions     []pkix.Extension      `asn1:"optional,tag:0"`
}

type pkiStatusInfo struct {
	Status       int
	StatusString []string       `asn1:"optional"`
	FailInfo     asn1.BitString `asn1:"optional"`
}

type timeStampResp struct {
	Status         pkiStatusInfo
	TimeStampToken asn1.RawValue `asn1:"optional"`
}

type contentInfo struct {
	ContentType asn1.ObjectIdentifier
	Content     asn1.RawValue `asn1:"explicit,tag:0"`
}

type encapsulatedContentInfo struct {
	EContentType asn1.ObjectIdentifier
	EContent     asn1.RawValue `asn1:"explicit,optional,tag:0"`
}

type signedData struct {
	Version          int
	DigestAlgorithms []pkix.AlgorithmIdentifier `asn1:"set"`
	EncapContentInfo encapsulatedContentInfo
	Certificates     asn1.RawValue `asn1:"optional,tag:0"`
	CRLs             asn1.RawValue `asn1:"optional,tag:1"`
	SignerInfos      []signerInfo  `asn1:"set"`
}

type signerInfo struct {
	Version            int
	SID                asn1.RawValue
	DigestAlgorithm    pkix.AlgorithmIdentifier
	SignedAttrs        asn1.RawValue `asn1:"optional,tag:0"`
	SignatureAlgorithm pkix.AlgorithmIdentifier
	Signature          []byte
	UnsignedAttrs      asn1.RawValue `asn1:"optional,tag:1"`
}

type issuerAndSerial struct {
	Issuer asn1.RawValue
	Serial *big.Int
}

type attribute struct {
	Type   asn1.ObjectIdentifier
	Values asn1.RawValue `asn1:"set"`
}

type accuracy struct {
	Seconds int `asn1:"optional"`
	Millis  int `asn1:"optional,tag:0"`
	Micros  int `asn1:"optional,tag:1"`
}

type tstInfo struct {
	Version        int
	Policy         asn1.ObjectIdentifier
	MessageImprint messageImprint
	SerialNumber   *big.Int
	GenTime        time.Time     `asn1:"generalized"`
	Accuracy       accuracy      `asn1:"optional"`
	Ordering       bool          `asn1:"optional"`
	Nonce          *big.Int      `asn1:"optional"`
	TSA            asn1.RawValue `asn1:"optional,tag:0"`
	Extensions     asn1.RawValue `asn1:"optional,tag:1"`
}

type essCertIDv2 struct {
	HashAlgorithm pkix.AlgorithmIdentifier `asn1:"optional"`
	CertHash      []byte
	IssuerSerial  asn1.RawValue `asn1:"optional"`
}

type signingCertificateV2 struct {
	Certs    []essCertIDv2
	Policies asn1.RawValue `asn1:"optional"`
}

type essCertID struct {
	CertHash     []byte
	IssuerSerial asn1.RawValue `asn1:"optional"`
}

type signingCertificate struct {
	Certs    []essCertID
	Policies asn1.RawValue `asn1:"optional"`
}

// ---- request -------------------------------------------------------------------------------------

// Request is one TimeStampReq as sent: the DER bytes and the nonce the reply must echo.
type Request struct {
	DER    []byte
	Nonce  *big.Int
	Digest []byte
}

// NewRequest builds a TimeStampReq (version 1) over a sha256 digest, with a fresh 64-bit nonce
// and certReq=true, so the reply carries the signer's certificate.
func NewRequest(digest []byte) (Request, error) {
	if len(digest) != crypto.SHA256.Size() {
		return Request{}, fmt.Errorf("%w: a sha256 digest is %d bytes", ErrMalformed, crypto.SHA256.Size())
	}
	nonce, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 63))
	if err != nil {
		return Request{}, fmt.Errorf("anchor: nonce: %w", err)
	}
	nonce.Add(nonce, big.NewInt(1)) // strictly positive, so it is never omitted as a zero value
	der, err := asn1.Marshal(timeStampReq{
		Version:        1,
		MessageImprint: messageImprint{HashAlgorithm: sha256AlgorithmIdentifer, HashedMessage: append([]byte(nil), digest...)},
		Nonce:          nonce,
		CertReq:        true,
	})
	if err != nil {
		return Request{}, fmt.Errorf("anchor: marshal request: %w", err)
	}
	return Request{DER: der, Nonce: nonce, Digest: append([]byte(nil), digest...)}, nil
}

// ParseRequest reads a TimeStampReq (the fake authority of the tests, and a verifier that wants
// to show what was asked). It accepts sha256 imprints only.
func ParseRequest(der []byte) (Request, error) {
	var req timeStampReq
	rest, err := asn1.Unmarshal(der, &req)
	if err != nil || len(rest) != 0 || req.Version != 1 {
		return Request{}, ErrMalformed
	}
	if !req.MessageImprint.HashAlgorithm.Algorithm.Equal(oidSHA256) || len(req.MessageImprint.HashedMessage) != crypto.SHA256.Size() {
		return Request{}, fmt.Errorf("%w: sha256 imprints only", ErrMalformed)
	}
	return Request{DER: der, Nonce: req.Nonce, Digest: req.MessageImprint.HashedMessage}, nil
}

// ---- reply ---------------------------------------------------------------------------------------

// PKIStatus values (RFC 3161 §2.4.2).
const (
	statusGranted         = 0
	statusGrantedWithMods = 1
)

// ParseResponse reads a TimeStampResp and returns the DER TimeStampToken. A refusal becomes
// ErrRejected with the status and the authority's failure bits — its free text is not quoted,
// because it is somebody else's string on its way into our rows.
func ParseResponse(der []byte) ([]byte, error) {
	var resp timeStampResp
	rest, err := asn1.Unmarshal(der, &resp)
	if err != nil || len(rest) != 0 {
		return nil, fmt.Errorf("%w: reply", ErrMalformed)
	}
	if resp.Status.Status != statusGranted && resp.Status.Status != statusGrantedWithMods {
		return nil, fmt.Errorf("%w: status %d%s", ErrRejected, resp.Status.Status, failInfo(resp.Status.FailInfo))
	}
	if len(resp.TimeStampToken.FullBytes) == 0 {
		return nil, fmt.Errorf("%w: a granted reply without a token", ErrMalformed)
	}
	return append([]byte(nil), resp.TimeStampToken.FullBytes...), nil
}

// failInfo names the PKIFailureInfo bits RFC 3161 defines.
func failInfo(b asn1.BitString) string {
	names := map[int]string{0: "badAlg", 2: "badRequest", 5: "badDataFormat", 14: "timeNotAvailable",
		15: "unacceptedPolicy", 16: "unacceptedExtension", 17: "addInfoNotAvailable", 25: "systemFailure"}
	var out []string
	for i := 0; i < b.BitLength; i++ {
		if b.At(i) == 1 {
			if n, ok := names[i]; ok {
				out = append(out, n)
			} else {
				out = append(out, fmt.Sprintf("bit%d", i))
			}
		}
	}
	if len(out) == 0 {
		return ""
	}
	return " (" + strings.Join(out, ", ") + ")"
}
