// Code generated by TestMirrorsMatchTheirSources from internal/anchor/verify.go; DO NOT EDIT.
// Regenerate: go test ./internal/verify -run TestMirrorsMatchTheirSources -update-mirror

package tsp

import (
	"bytes"
	"crypto"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"encoding/hex"
	"errors"
	"fmt"
	"math/big"
	"slices"
	"time"
)

// TokenInfo is what a verified token states.
type TokenInfo struct {
	// SignedAt is the authority's genTime (UTC): the time the receipt evidences.
	SignedAt time.Time
	// Serial is the authority's serial number of the token, in hex.
	Serial string
	// Policy is the authority's policy OID.
	Policy string
	// Digest is the sha256 the token covers.
	Digest []byte
	// Nonce is the nonce the token echoes (nil when the request carried none).
	Nonce *big.Int
	// Signer is the authority's signing certificate.
	Signer *x509.Certificate
	// Certificates are those the token carried (certReq=true), signer first.
	Certificates []*x509.Certificate
	// ChainVerified reports whether the signer chained to a trusted root at SignedAt.
	ChainVerified bool
	// RootSHA256 is the sha256 (hex) of the root the chain ended at, when verified.
	RootSHA256 string
}

// Verify checks a stored receipt offline: the token must be a CMS SignedData over a TSTInfo that
// covers exactly headHash (hex sha256), signed by a time-stamping certificate that chains to one
// of roots at the token's own genTime. certChain is the concatenated DER certificates stored with
// the token (it may be empty when the token carries them). roots is required: a verifier that
// trusted whatever certificate came with the token would verify a forgery just as happily.
//
// This is the function the tests and the offline verifier (wave 2) call; the anchoring path uses
// the same checks with the request's nonce added.
func Verify(token, certChain []byte, headHash string, roots *x509.CertPool) (TokenInfo, error) {
	if roots == nil {
		return TokenInfo{}, fmt.Errorf("%w: no trusted roots given", ErrUntrusted)
	}
	digest, err := decodeHeadHash(headHash)
	if err != nil {
		return TokenInfo{}, err
	}
	extra, err := parseCertChain(certChain)
	if err != nil {
		return TokenInfo{}, err
	}
	return verifyToken(token, extra, digest, nil, roots, true)
}

// CertChainDER concatenates certificates as stored in chain_anchors.cert_chain;
// x509.ParseCertificates reads it back.
func CertChainDER(certs []*x509.Certificate) []byte {
	var b bytes.Buffer
	for _, c := range certs {
		b.Write(c.Raw)
	}
	return b.Bytes()
}

func parseCertChain(der []byte) ([]*x509.Certificate, error) {
	if len(der) == 0 {
		return nil, nil
	}
	certs, err := x509.ParseCertificates(der)
	if err != nil {
		return nil, fmt.Errorf("%w: certificate chain", ErrMalformed)
	}
	return certs, nil
}

func decodeHeadHash(headHash string) ([]byte, error) {
	digest, err := hex.DecodeString(headHash)
	if err != nil || len(digest) != sha256.Size {
		return nil, fmt.Errorf("%w: a head hash is 64 hex characters", ErrMalformed)
	}
	return digest, nil
}

// verifyToken is the whole check. nonce nil skips the nonce comparison (a stored receipt, whose
// nonce was compared when it was taken). With requireChain false and no roots, the chain is tried
// against the system roots and ChainVerified reports the outcome instead of failing: the
// signature, the signed attributes, the signing-certificate binding and the time-stamping usage
// are checked either way.
func verifyToken(token []byte, extra []*x509.Certificate, digest []byte, nonce *big.Int, roots *x509.CertPool, requireChain bool) (TokenInfo, error) {
	p, err := parseToken(token)
	if err != nil {
		return TokenInfo{}, err
	}
	info := p.info
	if info.Version != 1 {
		return TokenInfo{}, fmt.Errorf("%w: TSTInfo version %d", ErrMalformed, info.Version)
	}
	if !info.MessageImprint.HashAlgorithm.Algorithm.Equal(oidSHA256) {
		return TokenInfo{}, fmt.Errorf("%w: the imprint is not sha256", ErrHashMismatch)
	}
	if !bytes.Equal(info.MessageImprint.HashedMessage, digest) {
		return TokenInfo{}, ErrHashMismatch
	}
	if nonce != nil && (info.Nonce == nil || info.Nonce.Cmp(nonce) != 0) {
		return TokenInfo{}, ErrNonceMismatch
	}

	candidates := append(slices.Clone(p.certs), extra...)
	signer, err := p.verifySignature(candidates)
	if err != nil {
		return TokenInfo{}, err
	}
	if err := checkTimeStampingUsage(signer); err != nil {
		return TokenInfo{}, err
	}

	out := TokenInfo{
		SignedAt: info.GenTime.UTC(), Serial: hex.EncodeToString(info.SerialNumber.Bytes()),
		Policy: info.Policy.String(), Digest: slices.Clone(digest), Nonce: info.Nonce,
		Signer: signer, Certificates: orderSignerFirst(p.certs, signer),
	}

	intermediates := x509.NewCertPool()
	for _, c := range candidates {
		if !c.Equal(signer) {
			intermediates.AddCert(c)
		}
	}
	pool := roots
	if pool == nil && !requireChain {
		if sys, err := x509.SystemCertPool(); err == nil {
			pool = sys
		}
	}
	if pool == nil {
		return out, nil
	}
	chains, err := signer.Verify(x509.VerifyOptions{
		Roots: pool, Intermediates: intermediates, CurrentTime: out.SignedAt,
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageTimeStamping},
	})
	if err != nil || len(chains) == 0 {
		if requireChain || roots != nil {
			return TokenInfo{}, fmt.Errorf("%w: %s", ErrUntrusted, chainErrorClass(err))
		}
		return out, nil
	}
	root := chains[0][len(chains[0])-1]
	sum := sha256.Sum256(root.Raw)
	out.ChainVerified = true
	out.RootSHA256 = hex.EncodeToString(sum[:])
	return out, nil
}

func chainErrorClass(err error) string {
	var unknown x509.UnknownAuthorityError
	var invalid x509.CertificateInvalidError
	switch {
	case err == nil:
		return "no chain"
	case errors.As(err, &unknown):
		return "unknown authority"
	case errors.As(err, &invalid):
		return "certificate invalid at the signed time"
	}
	return "chain does not verify"
}

// parsedToken is a TimeStampToken taken apart.
type parsedToken struct {
	sd       signedData
	eContent []byte
	info     tstInfo
	certs    []*x509.Certificate
	signer   signerInfo
}

func parseToken(token []byte) (parsedToken, error) {
	var p parsedToken
	var ci contentInfo
	rest, err := asn1.Unmarshal(token, &ci)
	if err != nil || len(rest) != 0 {
		return p, fmt.Errorf("%w: token", ErrMalformed)
	}
	if !ci.ContentType.Equal(oidSignedData) {
		return p, fmt.Errorf("%w: the token is not SignedData", ErrMalformed)
	}
	// encoding/asn1 does not unwrap an EXPLICIT tag into a RawValue: Bytes is the tagged content.
	if rest, err = asn1.Unmarshal(ci.Content.Bytes, &p.sd); err != nil || len(rest) != 0 {
		return p, fmt.Errorf("%w: SignedData", ErrMalformed)
	}
	if !p.sd.EncapContentInfo.EContentType.Equal(oidTSTInfo) {
		return p, fmt.Errorf("%w: the content is not a TSTInfo", ErrMalformed)
	}
	if p.eContent, err = octets(p.sd.EncapContentInfo.EContent); err != nil {
		return p, err
	}
	if rest, err = asn1.Unmarshal(p.eContent, &p.info); err != nil || len(rest) != 0 {
		return p, fmt.Errorf("%w: TSTInfo", ErrMalformed)
	}
	if p.info.SerialNumber == nil {
		return p, fmt.Errorf("%w: TSTInfo without a serial number", ErrMalformed)
	}
	if len(p.sd.Certificates.Bytes) > 0 {
		if p.certs, err = x509.ParseCertificates(p.sd.Certificates.Bytes); err != nil {
			return p, fmt.Errorf("%w: embedded certificates", ErrMalformed)
		}
	}
	// RFC 3161 §2.4.2: exactly one signer, the authority.
	if len(p.sd.SignerInfos) != 1 {
		return p, fmt.Errorf("%w: %d signers", ErrMalformed, len(p.sd.SignerInfos))
	}
	p.signer = p.sd.SignerInfos[0]
	return p, nil
}

// octets reads the eContent OCTET STRING, primitive or (BER) constructed from primitive pieces.
// explicit is the [0] EXPLICIT wrapper as encoding/asn1 leaves it in a RawValue.
func octets(explicit asn1.RawValue) ([]byte, error) {
	if len(explicit.Bytes) == 0 {
		return nil, fmt.Errorf("%w: the token carries no content", ErrMalformed)
	}
	var v asn1.RawValue
	if rest, err := asn1.Unmarshal(explicit.Bytes, &v); err != nil || len(rest) != 0 {
		return nil, fmt.Errorf("%w: eContent", ErrMalformed)
	}
	if v.Class != asn1.ClassUniversal || v.Tag != asn1.TagOctetString {
		return nil, fmt.Errorf("%w: eContent is not an OCTET STRING", ErrMalformed)
	}
	if !v.IsCompound {
		return v.Bytes, nil
	}
	var out []byte
	rest := v.Bytes
	for len(rest) > 0 {
		var part asn1.RawValue
		var err error
		if rest, err = asn1.Unmarshal(rest, &part); err != nil || part.Tag != asn1.TagOctetString || part.IsCompound {
			return nil, fmt.Errorf("%w: eContent pieces", ErrMalformed)
		}
		out = append(out, part.Bytes...)
	}
	return out, nil
}

// verifySignature finds the signer's certificate among candidates and verifies the signed
// attributes (content type, message digest, signing-certificate binding) and the signature.
func (p parsedToken) verifySignature(candidates []*x509.Certificate) (*x509.Certificate, error) {
	si := p.signer
	signer := findSigner(si.SID, candidates)
	if signer == nil {
		return nil, fmt.Errorf("%w: the signer's certificate is not in the token or the stored chain", ErrSignature)
	}
	hash, err := digestHash(si.DigestAlgorithm.Algorithm)
	if err != nil {
		return nil, err
	}
	// The envelope's digest list is not signed; it must at least name the signer's algorithm.
	if !slices.ContainsFunc(p.sd.DigestAlgorithms, func(a pkix.AlgorithmIdentifier) bool {
		return a.Algorithm.Equal(si.DigestAlgorithm.Algorithm)
	}) {
		return nil, fmt.Errorf("%w: the digest list does not name the signer's digest", ErrSignature)
	}
	// RFC 3161 tokens always carry signed attributes (the ESS signing certificate is mandatory).
	if len(si.SignedAttrs.FullBytes) == 0 {
		return nil, fmt.Errorf("%w: no signed attributes", ErrSignature)
	}
	attrs, err := parseAttributes(si.SignedAttrs.Bytes)
	if err != nil {
		return nil, err
	}
	var ct asn1.ObjectIdentifier
	if raw, ok := attrs[oidAttrContentType.String()]; !ok || unmarshalOne(raw, &ct) != nil || !ct.Equal(oidTSTInfo) {
		return nil, fmt.Errorf("%w: content-type attribute", ErrSignature)
	}
	var md []byte
	if raw, ok := attrs[oidAttrMessageDigest.String()]; !ok || unmarshalOne(raw, &md) != nil {
		return nil, fmt.Errorf("%w: message-digest attribute", ErrSignature)
	}
	h := hash.New()
	h.Write(p.eContent)
	if !bytes.Equal(h.Sum(nil), md) {
		return nil, fmt.Errorf("%w: message digest", ErrSignature)
	}
	if err := checkSigningCertificate(attrs, signer); err != nil {
		return nil, err
	}
	alg, err := signatureAlgorithm(si.SignatureAlgorithm.Algorithm, hash)
	if err != nil {
		return nil, err
	}
	// The signature covers the DER of the attributes as a SET OF, not as the [0] they are
	// tagged with inside SignerInfo (RFC 5652 §5.4).
	signed := slices.Clone(si.SignedAttrs.FullBytes)
	signed[0] = 0x31
	if err := signer.CheckSignature(alg, signed, si.Signature); err != nil {
		return nil, fmt.Errorf("%w: signature", ErrSignature)
	}
	return signer, nil
}

func findSigner(sid asn1.RawValue, candidates []*x509.Certificate) *x509.Certificate {
	switch {
	case sid.Class == asn1.ClassUniversal && sid.Tag == asn1.TagSequence:
		var ias issuerAndSerial
		if rest, err := asn1.Unmarshal(sid.FullBytes, &ias); err != nil || len(rest) != 0 || ias.Serial == nil {
			return nil
		}
		for _, c := range candidates {
			if bytes.Equal(c.RawIssuer, ias.Issuer.FullBytes) && c.SerialNumber.Cmp(ias.Serial) == 0 {
				return c
			}
		}
	case sid.Class == asn1.ClassContextSpecific && sid.Tag == 0 && !sid.IsCompound:
		for _, c := range candidates {
			if len(c.SubjectKeyId) > 0 && bytes.Equal(c.SubjectKeyId, sid.Bytes) {
				return c
			}
		}
	}
	return nil
}

// parseAttributes reads SignedAttributes into type → the single value's DER. A repeated type or
// an attribute with more than one value is refused (RFC 5652 §5.3).
func parseAttributes(der []byte) (map[string][]byte, error) {
	out := map[string][]byte{}
	rest := der
	for len(rest) > 0 {
		var a attribute
		var err error
		if rest, err = asn1.Unmarshal(rest, &a); err != nil {
			return nil, fmt.Errorf("%w: signed attributes", ErrSignature)
		}
		key := a.Type.String()
		if _, dup := out[key]; dup {
			return nil, fmt.Errorf("%w: repeated attribute %s", ErrSignature, key)
		}
		var v asn1.RawValue
		after, err := asn1.Unmarshal(a.Values.Bytes, &v)
		if err != nil || len(after) != 0 {
			return nil, fmt.Errorf("%w: attribute %s has not exactly one value", ErrSignature, key)
		}
		out[key] = v.FullBytes
	}
	return out, nil
}

func unmarshalOne(der []byte, v any) error {
	rest, err := asn1.Unmarshal(der, v)
	if err != nil {
		return err
	}
	if len(rest) != 0 {
		return ErrMalformed
	}
	return nil
}

// checkSigningCertificate binds the signature to the certificate that made it (ESS, RFC 2634 /
// RFC 5035): without it a second certificate over the same key could be swapped in.
func checkSigningCertificate(attrs map[string][]byte, signer *x509.Certificate) error {
	if raw, ok := attrs[oidAttrSigningCertV2.String()]; ok {
		var sc signingCertificateV2
		if unmarshalOne(raw, &sc) != nil || len(sc.Certs) == 0 {
			return fmt.Errorf("%w: signing-certificate-v2 attribute", ErrSignature)
		}
		alg := sc.Certs[0].HashAlgorithm.Algorithm
		hash := crypto.SHA256
		if len(alg) > 0 {
			var err error
			if hash, err = digestHash(alg); err != nil {
				return err
			}
		}
		h := hash.New()
		h.Write(signer.Raw)
		if !bytes.Equal(h.Sum(nil), sc.Certs[0].CertHash) {
			return fmt.Errorf("%w: the signing certificate does not match its binding", ErrSignature)
		}
		return nil
	}
	if raw, ok := attrs[oidAttrSigningCert.String()]; ok {
		var sc signingCertificate
		if unmarshalOne(raw, &sc) != nil || len(sc.Certs) == 0 || !crypto.SHA1.Available() {
			return fmt.Errorf("%w: signing-certificate attribute", ErrSignature)
		}
		// SHA-1 here identifies a certificate the signature already verified against; it is the
		// hash RFC 2634 fixes for this attribute, not a signature algorithm.
		h := crypto.SHA1.New()
		h.Write(signer.Raw)
		if !bytes.Equal(h.Sum(nil), sc.Certs[0].CertHash) {
			return fmt.Errorf("%w: the signing certificate does not match its binding", ErrSignature)
		}
		return nil
	}
	return fmt.Errorf("%w: no signing-certificate attribute", ErrSignature)
}

// checkTimeStampingUsage enforces RFC 3161 §2.3: the authority's certificate carries the
// time-stamping extended key usage, marked critical.
func checkTimeStampingUsage(c *x509.Certificate) error {
	if !slices.Contains(c.ExtKeyUsage, x509.ExtKeyUsageTimeStamping) {
		return fmt.Errorf("%w: not a time-stamping certificate", ErrUntrusted)
	}
	for _, ext := range c.Extensions {
		if ext.Id.Equal(oidExtKeyUsage) {
			if !ext.Critical {
				return fmt.Errorf("%w: the time-stamping usage is not critical", ErrUntrusted)
			}
			return nil
		}
	}
	return fmt.Errorf("%w: not a time-stamping certificate", ErrUntrusted)
}

func digestHash(oid asn1.ObjectIdentifier) (crypto.Hash, error) {
	switch {
	case oid.Equal(oidSHA256):
		return crypto.SHA256, nil
	case oid.Equal(oidSHA384):
		return crypto.SHA384, nil
	case oid.Equal(oidSHA512):
		return crypto.SHA512, nil
	case oid.Equal(oidSHA1):
		return 0, fmt.Errorf("%w: SHA-1 digests are refused", ErrSignature)
	}
	return 0, fmt.Errorf("%w: unsupported digest %s", ErrSignature, oid)
}

// signatureAlgorithm maps a CMS signature algorithm (which may name only the key type, with the
// digest given separately) onto crypto/x509's.
func signatureAlgorithm(oid asn1.ObjectIdentifier, hash crypto.Hash) (x509.SignatureAlgorithm, error) {
	byHash := func(a256, a384, a512 x509.SignatureAlgorithm) (x509.SignatureAlgorithm, error) {
		switch hash {
		case crypto.SHA256:
			return a256, nil
		case crypto.SHA384:
			return a384, nil
		case crypto.SHA512:
			return a512, nil
		}
		return x509.UnknownSignatureAlgorithm, fmt.Errorf("%w: unsupported digest", ErrSignature)
	}
	switch {
	case oid.Equal(oidRSAEncryption):
		return byHash(x509.SHA256WithRSA, x509.SHA384WithRSA, x509.SHA512WithRSA)
	case oid.Equal(oidSHA256WithRSA):
		return x509.SHA256WithRSA, nil
	case oid.Equal(oidSHA384WithRSA):
		return x509.SHA384WithRSA, nil
	case oid.Equal(oidSHA512WithRSA):
		return x509.SHA512WithRSA, nil
	case oid.Equal(oidRSAPSS):
		return byHash(x509.SHA256WithRSAPSS, x509.SHA384WithRSAPSS, x509.SHA512WithRSAPSS)
	case oid.Equal(oidECPublicKey):
		return byHash(x509.ECDSAWithSHA256, x509.ECDSAWithSHA384, x509.ECDSAWithSHA512)
	case oid.Equal(oidECDSAWithSHA256):
		return x509.ECDSAWithSHA256, nil
	case oid.Equal(oidECDSAWithSHA384):
		return x509.ECDSAWithSHA384, nil
	case oid.Equal(oidECDSAWithSHA512):
		return x509.ECDSAWithSHA512, nil
	case oid.Equal(oidEd25519):
		return x509.PureEd25519, nil
	}
	return x509.UnknownSignatureAlgorithm, fmt.Errorf("%w: unsupported signature algorithm %s", ErrSignature, oid)
}

func orderSignerFirst(certs []*x509.Certificate, signer *x509.Certificate) []*x509.Certificate {
	out := []*x509.Certificate{signer}
	for _, c := range certs {
		if !c.Equal(signer) {
			out = append(out, c)
		}
	}
	return out
}
